### ISSUE TITLE
warp+脚本貌似不起作用了

### ISSUE THREAD

**Issue by StephenAnboer** [yyuueexxiinngg/some-scripts#10]
Fake register的脚本好像没用了，运行了也不能新增流量了。

**Comment by yyuueexxiinngg** [comment]
经测试可用, 请确定输入了正确ID, 而且现在Cloudflare那边有Rate Limit, 只能慢慢跑了

**Comment by StephenAnboer** [comment]
> 经测试可用, 请确定输入了正确ID, 而且现在Cloudflare那边有Rate Limit, 只能慢慢跑了

试了下确实可以了，谢谢大佬
