### ISSUE TITLE
Add hcaptcha

### ISSUE THREAD

**Issue by hackgence** [yyuueexxiinngg/some-scripts#17]
add recaptcha or better add **hcaptcha** in the createteamdrive script

Thank you

**Comment by marcussacana** [comment]
why hcaptcha is better?

**Comment by hackgence-com** [comment]
there are many services that now can easily solve google's recaptcha, and when configured with bots will lead to a lot of spamming. hcaptcha is annoying to solve too :)

**Comment by ParveenBhadooOfficial** [comment]
@yyuueexxiinngg https://docs.hcaptcha.com
