### ISSUE TITLE
warp手机上可用了，脚本生成的还是不可用

### ISSUE THREAD

**Issue by fakegit** [yyuueexxiinngg/some-scripts#2]
希望能更新下，或者出个教程如何自己获取可用ip，谢谢了

**Comment by yyuueexxiinngg** [comment]
刚刚测试可用，是说获取Endpoint的IP嘛，那个没找到方法自己获取，手机可用获取是走了IPv6，试下WireGuard里设置成IPv6是否可用。

**Comment by fakegit** [comment]
发现改成ipv6确实可以用了~

就一个endpoint也太容易被针对了

**Comment by yyuueexxiinngg** [comment]
没办法，它初衷就不是为了这个 ¯\_( - _ - )_/¯
