### ISSUE TITLE
About https://gd.404edu.workers.dev/

### ISSUE THREAD

**Issue by SAOJSM** [yyuueexxiinngg/some-scripts#9]
MSGBOX "成功" but no display on drive

**Comment by yyuueexxiinngg** [comment]
Tested, works fine for me. Could you test again?
![chrome_BT8twwr0BH](https://user-images.githubusercontent.com/20928306/75839841-bc48f700-5e04-11ea-818e-bdcfa4080dbb.png)
![chrome_oJjVdi6maw](https://user-images.githubusercontent.com/20928306/75839870-ca971300-5e04-11ea-84f2-f95678225ac5.png)

**Comment by SAOJSM** [comment]
Yes, Msgbox display "成功" but nothing display on teamdrive page. You can check it

**Comment by yyuueexxiinngg** [comment]
> Yes, Msgbox display "成功" but nothing display on teamdrive page. You can check it

Tested again, still working for me. Both trials created teamdrive for me and they do show up on my teamdrive page. To make things clear, this worker creates a teamdrive then share it with the input email. Did you input the correct email and check teamdrive within that account? 

If it's still not working for you, could you please provide the backend logs and your Gmail? 
Go to Cloudflare workers and edit this worker, then make a request from the preview section. The logs will show up in the console.
You can email me your Gmail if you don't want to post it here publicly.

**Comment by SAOJSM** [comment]
OK, I try again and work. Thank you
